version: '2'
services:
  odoo11:
    image: odoo:11.0
    ports:
      - "8070:8069"
    tty: true
    command: -- --dev=reload
#    command: odoo scaffold /mnt/extra-addons/test_module
    volumes:
      - /home/felappi/docker/odoo11/logs:/var/log/odoo
      - /home/felappi/docker/odoo11/conf:/etc/odoo
      - /home/felappi/docker/odoo11/extra-addons:/mnt/extra-addons

    restart: always             # run as a service  