version: '2'
services:
  web:
    image: odoo:11.0
    ports:
      - 89:8069
      - 71:8071
      - 72:8072
    tty: true
    command: -- --dev=reload
#    command: odoo scaffold /mnt/extra-addons/test_module
    volumes:
      - /home/felappi/docker/odoo11/logs:/var/log/odoo
      - /home/felappi/docker/odoo11/conf:/etc/odoo
      - /home/felappi/docker/odoo11/extra-addons:/mnt/extra-addons

    restart: always       # run as a service  