version: '2'
services:
    web:
        container_name: odoo_web
        build:
            context: .
            dockerfile: Dockerfile-odoo
        volumes:
            - /home/felappi/docker/odoo11/logs:/var/log/odoo
            - /home/felappi/docker/odoo11/data:/var/lib/odoo
            - /home/felappi/docker/odoo11/extra-addons:/mnt/addons
        # command: -- --dev=reload
        command: odoo -d Pneus -u all
    proxy:
        depends_on:
            - web
        container_name: odoo_proxy
        build:
            context: .
            dockerfile: Dockerfile-nginx
        ports:
            - "8069:8069"