FROM odoo:11.0

USER root
RUN rm -f /etc/apt/sources.list && touch /etc/apt/sources.list
RUN echo 'deb http://archive.debian.org/debian/ stretch main contrib non-free' > /etc/apt/sources.list
RUN echo 'deb http://archive.debian.org/debian-security/ stretch/updates main non-free contrib' >> /etc/apt/sources.list
RUN rm -f /etc/apt/sources.list.d/* && touch /etc/apt/sources.list.d/backports.list
RUN echo 'deb http://archive.debian.org/debian stretch-backports main' >> /etc/apt/sources.list.d/backports.list
RUN apt-get update
RUN apt-get install git zip -y
# Copy the key content, such as the config file and the enterprise addons
COPY ./odoo.conf /etc/odoo/odoo.conf
COPY ./requirements.txt /etc/odoo/requirements.txt
COPY ./sp_api.zip /etc/odoo/sp_api.zip
RUN export PIP_DISABLE_PIP_VERSION_CHECK=1
RUN pip3 install --upgrade pip -q
RUN pip3 install -r /etc/odoo/requirements.txt
RUN pip3 install paramiko==2.9.2 --prefer-binary
# RUN rm -f /usr/local/lib/python3.5/dist-packages/sp_api
RUN unzip -oq /etc/odoo/sp_api.zip -d /usr/local/lib/python3.5/dist-packages/ 
RUN chown odoo:odoo -R /etc/odoo/
USER odoo
EXPOSE 8072
